repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: generate-manpage
    name: generate manpage
    language: python
    additional_dependencies:
      - argparse_manpage
      - websocket-client
    entry: ./man/build.py
    files: (zeekclient/cli\.py|man/build\.py)$
